spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  application.name: payment
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8050
#  servlet.context-path: /api/v1

logging:
  level:
    ru.bmstu: TRACE

api:
  url:
    base: /api/v1/payments