spring:
  application.name: CarService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  url:
    base: /api/v1/cars
logging:
  level:
    org.example: TRACE
server:
  port: 8070