spring.application.name: GatewayService

server:
  port: 8080

breaker:
  threshold: 3

manage:
  urls:
    cars: "http://cars:8070/manage/health"
    rental: "http://rental:8060/manage/health"
    payment: "http://payment:8050/manage/health"


services:
  payment:
    url:
      base: "/api/v1/payments"
  cars:
    url:
      base: "/api/v1/cars"
  rental:
    url:
      base: "/api/v1/rental"


feign:
  okhttp:
    enabled: true
  payment:
#    url: "http://payment:8050"
      url: "http://localhost:8050"
  cars:
#    url: "http://cars:8070"
      url: "http://localhost:8070"
  rental:
#    url: "http://rental:8060"
    url: "http://localhost:8060"